package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type EnvVar struct{ID int64 `json:"id"`;Environment string `json:"environment"`;Key string `json:"key"`;Value string `json:"value"`;ChangedBy string `json:"changed_by"`;UpdatedAt time.Time `json:"updated_at"`;CreatedAt time.Time `json:"created_at"`}
type Change struct{ID int64 `json:"id"`;Environment string `json:"environment"`;Key string `json:"key"`;OldValue string `json:"old_value"`;NewValue string `json:"new_value"`;ChangedBy string `json:"changed_by"`;ChangedAt time.Time `json:"changed_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"bandolier.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS env_vars(id INTEGER PRIMARY KEY AUTOINCREMENT,environment TEXT NOT NULL,key TEXT NOT NULL,value TEXT DEFAULT '',changed_by TEXT DEFAULT '',updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,created_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(environment,key));CREATE TABLE IF NOT EXISTS changes(id INTEGER PRIMARY KEY AUTOINCREMENT,environment TEXT NOT NULL,key TEXT NOT NULL,old_value TEXT DEFAULT '',new_value TEXT NOT NULL,changed_by TEXT DEFAULT '',changed_at DATETIME DEFAULT CURRENT_TIMESTAMP)`)}
func(db *DB)Set(env,key,value,changedBy string)error{var old string;db.QueryRow(`SELECT value FROM env_vars WHERE environment=? AND key=?`,env,key).Scan(&old);_,err:=db.Exec(`INSERT INTO env_vars(environment,key,value,changed_by,updated_at)VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(environment,key) DO UPDATE SET value=excluded.value,changed_by=excluded.changed_by,updated_at=CURRENT_TIMESTAMP`,env,key,value,changedBy);if err!=nil{return err};db.Exec(`INSERT INTO changes(environment,key,old_value,new_value,changed_by)VALUES(?,?,?,?,?)`,env,key,old,value,changedBy);return nil}
func(db *DB)List(env string)([]EnvVar,error){rows,_:=db.Query(`SELECT id,environment,key,value,changed_by,updated_at,created_at FROM env_vars WHERE environment=? ORDER BY key`,env);defer rows.Close();var out[]EnvVar;for rows.Next(){var v EnvVar;rows.Scan(&v.ID,&v.Environment,&v.Key,&v.Value,&v.ChangedBy,&v.UpdatedAt,&v.CreatedAt);out=append(out,v)};return out,nil}
func(db *DB)ListEnvs()([]string,error){rows,_:=db.Query(`SELECT DISTINCT environment FROM env_vars ORDER BY environment`);defer rows.Close();var out[]string;for rows.Next(){var e string;rows.Scan(&e);out=append(out,e)};return out,nil}
func(db *DB)History(env,key string)([]Change,error){rows,_:=db.Query(`SELECT id,environment,key,old_value,new_value,changed_by,changed_at FROM changes WHERE environment=? AND key=? ORDER BY changed_at DESC LIMIT 50`,env,key);defer rows.Close();var out[]Change;for rows.Next(){var c Change;rows.Scan(&c.ID,&c.Environment,&c.Key,&c.OldValue,&c.NewValue,&c.ChangedBy,&c.ChangedAt);out=append(out,c)};return out,nil}
func(db *DB)Delete(env,key string){db.Exec(`DELETE FROM env_vars WHERE environment=? AND key=?`,env,key)}
func(db *DB)Stats()(map[string]interface{},error){var vars,envs int;db.QueryRow(`SELECT COUNT(*) FROM env_vars`).Scan(&vars);db.QueryRow(`SELECT COUNT(DISTINCT environment) FROM env_vars`).Scan(&envs);return map[string]interface{}{"total_vars":vars,"environments":envs},nil}
